### ISSUE TITLE
Looks like DELETE method is unsupported

### ISSUE THREAD

**Issue by noahamar** [jserver/mock-s3#6]
Hi Joe,

It appears that mock-s3 doesn't support DELETE method requests to delete objects. I use boto and it gives the error:

S3ResponseError: S3ResponseError: 501 Unsupported method ('DELETE')

Would you know how I could solve this? Thanks a lot!

**Comment by jserver** [comment]
I just committed a patch that adds that functionality, let me know if that works for you...
